services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: kcdle_app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  scheduler:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: kcdle_scheduler
    command: >
      sh -c "while true; do
        php backend/artisan schedule:run;
        sleep 60;
      done"
    volumes:
      - .:/var/www/html
    depends_on:
      - app

  nginx:
    image: nginx:1.27
    container_name: kcdle_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: kcdle_db
    environment:
      POSTGRES_DB: kcdle
      POSTGRES_USER: kcdle
      POSTGRES_PASSWORD: kcdle
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
